// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBESUFun6rj1Yc_8Pw2MPhwtEsZsFPAobA',
    appId: '1:96955088288:web:77f399d01344888a2038c5',
    messagingSenderId: '96955088288',
    projectId: 'antrean-online-e0060',
    authDomain: 'antrean-online-e0060.firebaseapp.com',
    storageBucket: 'antrean-online-e0060.firebasestorage.app',
    measurementId: 'G-5GLP2ST81P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2jxOIcZd7g-Iceo9ByD6hGbQboU9rJhg',
    appId: '1:96955088288:android:d9e1fd53902dbb1e2038c5',
    messagingSenderId: '96955088288',
    projectId: 'antrean-online-e0060',
    storageBucket: 'antrean-online-e0060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUKcVuzm6jdmmJ-BFoaH1j3f0hPn2r_pY',
    appId: '1:96955088288:ios:88bab40ff742a68c2038c5',
    messagingSenderId: '96955088288',
    projectId: 'antrean-online-e0060',
    storageBucket: 'antrean-online-e0060.firebasestorage.app',
    iosBundleId: 'com.example.antreanOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUKcVuzm6jdmmJ-BFoaH1j3f0hPn2r_pY',
    appId: '1:96955088288:ios:88bab40ff742a68c2038c5',
    messagingSenderId: '96955088288',
    projectId: 'antrean-online-e0060',
    storageBucket: 'antrean-online-e0060.firebasestorage.app',
    iosBundleId: 'com.example.antreanOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBESUFun6rj1Yc_8Pw2MPhwtEsZsFPAobA',
    appId: '1:96955088288:web:d48b34141cb6bbdf2038c5',
    messagingSenderId: '96955088288',
    projectId: 'antrean-online-e0060',
    authDomain: 'antrean-online-e0060.firebaseapp.com',
    storageBucket: 'antrean-online-e0060.firebasestorage.app',
    measurementId: 'G-8PS0S84H0L',
  );
}
